### ISSUE TITLE
BUG: render.Text crashes when vendoring

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#120]
Minimal reproduction program:
```go
package main

import (
	"github.com/oakmound/oak/v2"
	"github.com/oakmound/oak/v2/render"
	"github.com/oakmound/oak/v2/scene"
)

func main() {
	var text *render.Text
	oak.Add("test",
		func(prevScene string, data interface{}) {
			text = render.NewStrText("hello", 10, 10)
			render.Draw(text)
		},
		func() bool {return true},
		func() (string, *scene.Result) {return "",nil},
	)
	oak.Init("test")
}
```

This program works fine normally, but after running `go mod vendor` it crashes:
```
[oak]-------- No logs directory found. No logs will be written to file.
[config:207]  ERROR:[{{assets/ audio/ images/ font/} { ERROR} {0 0 480 640 1} {none 12 72  white} 60 60 English 

~~~~~~~~~~~~~~~
Oak Seed: 1595787410173448998

~~~~~~~~~~~~~~~
[font:185]  ERROR:[open /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/render/default_assets/font/luxisr.ttf: no such file or directory] 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56d36f]

goroutine 23 [running]:
github.com/oakmound/oak/v2/render.(*Text).GetDims(0xc0000f6200, 0x4024000000000000, 0xc0000f6200)
        /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/render/text.go:77 +0x2f
github.com/oakmound/oak/v2/render.(*RenderableHeap).draw(0xc0000c4aa0, 0x6fbc20, 0xc0001aa0b8, 0x0, 0x0, 0x280, 0x1e0)
        /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/render/drawHeap.go:141 +0x29a
github.com/oakmound/oak/v2/render.(*DrawStack).Draw(0xc0000f6140, 0x6fbc20, 0xc0001aa0b8, 0x0, 0x0, 0x280, 0x1e0)
        /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/render/drawStack.go:58 +0xae
github.com/oakmound/oak/v2.drawLoop()
        /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/drawLoop.go:73 +0x4a6
created by github.com/oakmound/oak/v2.lifecycleLoop
        /home/binarycat/github-go/oak-font-bug/vendor/github.com/oakmound/oak/v2/lifecycle.go:42 +0x2bf
exit status 2
```

After some digging around, I found that it wanted a file at `assets/font/luxisr.ttf`. Putting any font there seemed to fix the issue, but now I'm getting a similar crash, but this time I can't find the source, even after looking around with `delve` (the 200+ goroutines didn't help).

**Comment by 200sc** [comment]
It looks like vendoring strips the default font file we ship with from our default assets directory. We might be able to encode the file in go code, but it depends on how extensible the font library we're using is for file sources. 

A workaround is avoiding the default font and specifying a font file of your own (which could be a copy of the font we include).

**Comment by 200sc** [comment]
We can address this by embedding the default font bytes into the binary. Should be a quick fix.
